#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-eddington
Version  : 2.1.1
Release  : 21
URL      : https://cran.r-project.org/src/contrib/eddington_2.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/eddington_2.1.1.tar.gz
Summary  : Compute a Cyclist's Eddington Number
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-eddington-lib = %{version}-%{release}
Requires: R-Rcpp
BuildRequires : R-Rcpp
BuildRequires : buildreq-R

%description
computing cumulative E over a vector. A cyclist's Eddington number

%package lib
Summary: lib components for the R-eddington package.
Group: Libraries

%description lib
lib components for the R-eddington package.


%prep
%setup -q -c -n eddington
cd %{_builddir}/eddington

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641006099

%install
export SOURCE_DATE_EPOCH=1641006099
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library eddington
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library eddington
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library eddington
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc eddington || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/eddington/DESCRIPTION
/usr/lib64/R/library/eddington/INDEX
/usr/lib64/R/library/eddington/Meta/Rd.rds
/usr/lib64/R/library/eddington/Meta/data.rds
/usr/lib64/R/library/eddington/Meta/features.rds
/usr/lib64/R/library/eddington/Meta/hsearch.rds
/usr/lib64/R/library/eddington/Meta/links.rds
/usr/lib64/R/library/eddington/Meta/nsInfo.rds
/usr/lib64/R/library/eddington/Meta/package.rds
/usr/lib64/R/library/eddington/Meta/vignette.rds
/usr/lib64/R/library/eddington/NAMESPACE
/usr/lib64/R/library/eddington/NEWS.md
/usr/lib64/R/library/eddington/R/eddington
/usr/lib64/R/library/eddington/R/eddington.rdb
/usr/lib64/R/library/eddington/R/eddington.rdx
/usr/lib64/R/library/eddington/data/Rdata.rdb
/usr/lib64/R/library/eddington/data/Rdata.rds
/usr/lib64/R/library/eddington/data/Rdata.rdx
/usr/lib64/R/library/eddington/doc/eddington.R
/usr/lib64/R/library/eddington/doc/eddington.Rmd
/usr/lib64/R/library/eddington/doc/eddington.html
/usr/lib64/R/library/eddington/doc/index.html
/usr/lib64/R/library/eddington/help/AnIndex
/usr/lib64/R/library/eddington/help/aliases.rds
/usr/lib64/R/library/eddington/help/eddington.rdb
/usr/lib64/R/library/eddington/help/eddington.rdx
/usr/lib64/R/library/eddington/help/paths.rds
/usr/lib64/R/library/eddington/html/00Index.html
/usr/lib64/R/library/eddington/html/R.css
/usr/lib64/R/library/eddington/include/eddington.h
/usr/lib64/R/library/eddington/include/eddington_RcppExports.h
/usr/lib64/R/library/eddington/tests/testthat.R
/usr/lib64/R/library/eddington/tests/testthat/refdata.rds
/usr/lib64/R/library/eddington/tests/testthat/simdata.rds
/usr/lib64/R/library/eddington/tests/testthat/test-package.r

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/eddington/libs/eddington.so
/usr/lib64/R/library/eddington/libs/eddington.so.avx2
/usr/lib64/R/library/eddington/libs/eddington.so.avx512
